export enum tagTypes {
  user = 'user',
  product = 'product',
  customer = 'customer',
  purchase = 'purchase',
  sell = 'sell',
  return = 'return',
  supplier = 'supplier',
  vats = 'vats',
  discounts = 'discounts',
  color = 'color',
  unit = 'unit',
  category = 'category',
  brand = 'brand',
  supplierPayments = 'supplierPayments',
  variants = 'variants',
  customerPayments = 'customerPayments',
  currencyType = 'currencyType',
  supplierSells = 'supplierSells',
}

export const tagTypeLists = [
  tagTypes.user,
  tagTypes.product,
  tagTypes.customer,
  tagTypes.purchase,
  tagTypes.sell,
  tagTypes.return,
  tagTypes.supplier,
  tagTypes.vats,
  tagTypes.discounts,
  tagTypes.color,
  tagTypes.unit,
  tagTypes.category,
  tagTypes.brand,
  tagTypes.supplier,
  tagTypes.supplierPayments,
  tagTypes.variants,
  tagTypes.customerPayments,
  tagTypes.currencyType,
  tagTypes.supplierSells,
]
