export enum tagTypes {
  user = 'user',
  product = 'product',
  customer = 'customer',
  purchase = 'purchase',
  sell = 'sell',
  return = 'return',
  supplier = 'supplier',
  vats = 'vats',
  discounts = 'discounts',
  color = 'color',
  unit = 'unit',
  category = 'category',
  brand = 'brand',
  supplierPayments = 'supplierPayments',
  variants = 'variants',
  customerPayments = 'customerPayments',
  currencyType = 'currencyType',
  supplierSells = 'supplierSells',
  supplierSellVariants = 'supplierSellVariants',
  supplierSellProducts = 'supplierSellProducts',
  purchaseGroup = 'purchaseGroup',
  sellGroup = 'sellGroup',
  payInSupplier = 'payInSupplier',
  customerPurchase = 'customerPurchase',
  customerPayInUser = 'customerPayInUser',
  returnGroup = 'returnGroup',
  supplierReturnPayment = 'supplierReturnPayment',
  additionalMoneyBack = 'additionalMoneyBack',
  additionalExpense = 'additionalExpense',
}

export const tagTypeLists = [
  tagTypes.user,
  tagTypes.product,
  tagTypes.customer,
  tagTypes.purchase,
  tagTypes.sell,
  tagTypes.return,
  tagTypes.supplier,
  tagTypes.vats,
  tagTypes.discounts,
  tagTypes.color,
  tagTypes.unit,
  tagTypes.category,
  tagTypes.brand,
  tagTypes.supplier,
  tagTypes.supplierPayments,
  tagTypes.variants,
  tagTypes.customerPayments,
  tagTypes.currencyType,
  tagTypes.supplierSells,
  tagTypes.customerPurchase,
  tagTypes.payInSupplier,
  tagTypes.sellGroup,
  tagTypes.supplierSellProducts,
  tagTypes.supplierSellVariants,
  tagTypes.purchaseGroup,
  tagTypes.customerPayInUser,
  tagTypes.returnGroup,
  tagTypes.supplierReturnPayment,
  tagTypes.additionalMoneyBack,
  tagTypes.additionalExpense,
]
